### ISSUE TITLE
Pridat Markiza International

### ISSUE THREAD

**Issue by jdemovic** [cache-sk/kodirepo#1]
Ahoj, bolo by mozne pridat markiza international ?
dakujem
J

**Comment by sleduj-tv** [comment]
Nie, pretoze toto nie je z nelegalnych zdrojov...
Zaplat si alebo si najdi sam

**Comment by jdemovic** [comment]
zaplatene samozrejme mam, len nie na KODI :) a urcite by som to nechcel nelegalne

**Comment by sleduj-tv** [comment]
v tom pripade existuju kodi doplnky
![image](https://github.com/cache-sk/kodirepo/assets/106910269/853eb315-e6ca-4a5a-bfca-b2a3f4e7ddf3)

**Comment by cache-sk** [comment]
Sry pani, mal som omylom unwatch na repository :)

Kazdopadne taketo requesty patria do freeview, nie do repa.

Ak niekde "vysiela" Markiza International verejne stream, mozem ju pridat, avsak pokial viem, je len v platenom Voyo a z neho bez (plateneho) prihlasenia stream nevydolujem.

Rozne nelegalne a uniknute streamy nepridavam, len oficialne, ktore dokazem ziskat zo stranok bez plateneho konta.
