### ISSUE TITLE
Stránka na zdroj nefunguje

### ISSUE THREAD

**Issue by djkakadu** [cache-sk/kodirepo#2]
Zdar.
Odkaz na zdroj súborov nefunguje: http://p.xf.cz/r/
Hosting?

**Comment by cache-sk** [comment]
Webzdarma zaviedol limit na prenasane data, kedze stranka je pouzivana aj pre prima proxy, tak tie data su uz vycerpane.

Riesim alternativny free hosting pre to proxy, kazdopadne repo odkaz nebude minimalne do 1.2. fungovat, kym sa data limiter na WZ neresetuje.

Je mozne pouzit dlhsiu alternativu - https://cache-sk.github.io/kodirepo
